/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class com_aijiao_test_SerialPort */

#ifndef _Included_com_aijiao_test_SerialPort
#define _Included_com_aijiao_test_SerialPort
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_aijiao_test_SerialPort
 * Method:    getPorts
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_com_aijiao_test_SerialPort_getPorts
  (JNIEnv *, jobject);

/*
 * Class:     com_aijiao_test_SerialPort
 * Method:    getHandle
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_aijiao_test_SerialPort_getHandle
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_aijiao_test_SerialPort
 * Method:    startPort
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_com_aijiao_test_SerialPort_startPort
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     com_aijiao_test_SerialPort
 * Method:    readPort
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_aijiao_test_SerialPort_readPort
  (JNIEnv *, jobject);

/*
 * Class:     com_aijiao_test_SerialPort
 * Method:    sendDatatoP04
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_aijiao_test_SerialPort_sendDatatoP04
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
